// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAI.Service.Core.Infrastructure.Persistencia;

#nullable disable

namespace SAI.Service.Core.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(SaiDbContext))]
    [Migration("20260723030000_EsquemaPruebaApagado")]
    partial class EsquemaPruebaApagado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Acciones.Accion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventoDisparoCodigo")
                        .HasColumnType("TEXT");

                    b.Property<long>("Instante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModalidadEfectiva")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModalidadSolicitada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoReservadoSeg")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.HasIndex("DispositivoCodigo", "Instante");

                    b.ToTable("Accion", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.Fabricante", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Identificado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Fabricante", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloBateria", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CapacidadAh")
                        .HasColumnType("REAL");

                    b.Property<string>("FabricanteCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tecnologia")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TemperaturaReferenciaC")
                        .HasColumnType("REAL");

                    b.Property<double?>("TensionNominalV")
                        .HasColumnType("REAL");

                    b.Property<double?>("VidaFlotacionAniosMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("VidaFlotacionAniosMin")
                        .HasColumnType("REAL");

                    b.HasKey("Codigo");

                    b.HasIndex("FabricanteCodigo");

                    b.ToTable("ModeloBateria", null, t =>
                        {
                            t.HasCheckConstraint("CK_ModeloBateria_VidaTemp", "\"VidaFlotacionAniosMin\" IS NULL AND \"VidaFlotacionAniosMax\" IS NULL OR \"TemperaturaReferenciaC\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloDispositivo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FabricanteCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineaTopologia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TensionNominalV")
                        .HasColumnType("REAL");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PotenciaVaNominal", "SAI.Service.Core.Domain.Catalogo.ModeloDispositivo.PotenciaVaNominal#Valor<double>", b1 =>
                        {
                            b1.Property<double>("Contenido")
                                .HasColumnType("REAL")
                                .HasColumnName("PotenciaVaNominalValor");

                            b1.Property<string>("Origen")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PotenciaVaNominalOrigen");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("FabricanteCodigo");

                    b.ToTable("ModeloDispositivo", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Intervenciones.FichaVidaUtil", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("BateriaCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CumplioExpectativa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesvioDias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasEnServicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuenteCotizacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntervencionCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VidaEsperadaDias")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CostoPorAnioServicio", "SAI.Service.Core.Domain.Intervenciones.FichaVidaUtil.CostoPorAnioServicio#Dinero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("TEXT")
                                .HasColumnName("CostoAnioFecha");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CostoAnioMoneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("TEXT")
                                .HasColumnName("CostoAnioMonto");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CostoPorAnioServicioUsd", "SAI.Service.Core.Domain.Intervenciones.FichaVidaUtil.CostoPorAnioServicioUsd#Dinero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("TEXT")
                                .HasColumnName("CostoAnioUsdFecha");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CostoAnioUsdMoneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("TEXT")
                                .HasColumnName("CostoAnioUsdMonto");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("IntervencionCodigo");

                    b.HasIndex("DispositivoCodigo", "IntervencionCodigo");

                    b.ToTable("FichaVidaUtil", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Intervenciones.Intervencion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("BateriaEntranteCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BateriaSalienteCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ejecutor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hallazgos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InstanteOcurrido")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InstanteRegistrado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Disposicion", "SAI.Service.Core.Domain.Intervenciones.Intervencion.Disposicion#DisposicionFinal", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Destino")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DisposicionDestino");

                            b1.Property<string>("Receptor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DisposicionReceptor");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ManoDeObra", "SAI.Service.Core.Domain.Intervenciones.Intervencion.ManoDeObra#Dinero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("TEXT")
                                .HasColumnName("ManoObraFecha");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ManoObraMoneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("TEXT")
                                .HasColumnName("ManoObraMonto");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Repuestos", "SAI.Service.Core.Domain.Intervenciones.Intervencion.Repuestos#Dinero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("TEXT")
                                .HasColumnName("RepuestosFecha");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("RepuestosMoneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("TEXT")
                                .HasColumnName("RepuestosMonto");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Total", "SAI.Service.Core.Domain.Intervenciones.Intervencion.Total#Dinero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalFecha");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalMoneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalMonto");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("DispositivoCodigo", "InstanteOcurrido");

                    b.ToTable("Intervencion", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.UnidadFisica", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FechaBaja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoBaja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("Tipo", "Estado");

                    b.ToTable("UnidadFisica", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator<string>("Tipo").HasValue("UnidadFisica");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.Agregado", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Advertencia")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cobertura")
                        .HasColumnType("REAL");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Maximo")
                        .HasColumnType("REAL");

                    b.Property<double?>("Minimo")
                        .HasColumnType("REAL");

                    b.Property<int>("NMuestras")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Promedio")
                        .HasColumnType("REAL");

                    b.Property<string>("Variable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VentanaDuracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("VentanaInicio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.HasIndex("DispositivoCodigo", "Variable", "VentanaInicio")
                        .IsUnique();

                    b.ToTable("Agregado", null, t =>
                        {
                            t.HasCheckConstraint("CK_Agregado_Cobertura", "\"Cobertura\" >= 0 AND \"Cobertura\" <= 1");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.Evento", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DuracionSeg")
                        .HasColumnType("REAL");

                    b.Property<double?>("IncertidumbreDuracionSeg")
                        .HasColumnType("REAL");

                    b.Property<long>("Instante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReglaDerivacionCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReglaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("DispositivoCodigo", "Instante");

                    b.HasIndex("ReglaDerivacionCodigo", "ReglaVersion");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.FuenteDatos", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfianzaBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("FuenteDatos", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.Muestra", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Instante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lecturas")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Valores");

                    b.Property<string>("SesionSondeoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("SesionSondeoCodigo");

                    b.HasIndex("DispositivoCodigo", "Instante");

                    b.ToTable("Muestra", null, t =>
                        {
                            t.HasCheckConstraint("CK_Muestra_Calidad", "\"Calidad\" IN ('Completa','Parcial','Perdida')");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.PruebaBateria", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CargaPorcentaje")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Comparable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Confianza")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Instante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MontajeBateriaCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Veredicto")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CaidaTension", "SAI.Service.Core.Domain.Monitoreo.PruebaBateria.CaidaTension#Valor<double?>", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double?>("Contenido")
                                .HasColumnType("REAL")
                                .HasColumnName("CaidaTensionValor");

                            b1.Property<string>("Origen")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CaidaTensionOrigen");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("MontajeBateriaCodigo");

                    b.HasIndex("DispositivoCodigo", "Instante");

                    b.ToTable("PruebaBateria", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.ReglaDerivacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parametros")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Parametros");

                    b.Property<long>("VigenteDesde")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo", "Version");

                    b.ToTable("ReglaDerivacion", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.SesionSondeo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dialecto")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuenteDatosCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervaloSeg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapaVariableOrigen")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MapaVariableOrigen");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Vigencia", "SAI.Service.Core.Domain.Monitoreo.SesionSondeo.Vigencia#Vigencia", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Desde")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Desde");

                            b1.Property<long?>("Hasta")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Hasta");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("DispositivoCodigo");

                    b.HasIndex("FuenteDatosCodigo");

                    b.ToTable("SesionSondeo", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Verificaciones.Verificacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActualizadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PruebaEnCursoDesde")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Supuesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("VigenciaHasta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.ToTable("Verificacion", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.CoberturaHost", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Vigencia", "SAI.Service.Core.Domain.Vinculos.CoberturaHost.Vigencia#Vigencia", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Desde")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Desde");

                            b1.Property<long?>("Hasta")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Hasta");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("DispositivoCodigo");

                    b.HasIndex("HostCodigo")
                        .IsUnique()
                        .HasFilter("\"Hasta\" IS NULL");

                    b.ToTable("CoberturaHost", null, t =>
                        {
                            t.HasCheckConstraint("CK_CoberturaHost_Intervalo", "\"Hasta\" IS NULL OR \"Hasta\" >= \"Desde\"");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.MontajeBateria", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("BateriaCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Vigencia", "SAI.Service.Core.Domain.Vinculos.MontajeBateria.Vigencia#Vigencia", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Desde")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Desde");

                            b1.Property<long?>("Hasta")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Hasta");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("BateriaCodigo");

                    b.HasIndex("DispositivoCodigo", "Posicion")
                        .IsUnique()
                        .HasFilter("\"Hasta\" IS NULL");

                    b.ToTable("MontajeBateria", null, t =>
                        {
                            t.HasCheckConstraint("CK_MontajeBateria_Intervalo", "\"Hasta\" IS NULL OR \"Hasta\" >= \"Desde\"");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Bateria", b =>
                {
                    b.HasBaseType("SAI.Service.Core.Domain.Inventario.UnidadFisica");

                    b.Property<DateOnly?>("FechaCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaFabricacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloBateriaCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("ModeloBateriaCodigo");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Bateria");
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Dispositivo", b =>
                {
                    b.HasBaseType("SAI.Service.Core.Domain.Inventario.UnidadFisica");

                    b.Property<string>("ModeloDispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("TEXT");

                    b.HasIndex("ModeloDispositivoCodigo");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Dispositivo");
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Host", b =>
                {
                    b.HasBaseType("SAI.Service.Core.Domain.Inventario.UnidadFisica");

                    b.Property<string>("Criticidad")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EnServicioDesde")
                        .HasColumnType("INTEGER");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Host");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Acciones.Accion", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloBateria", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.Fabricante", null)
                        .WithMany()
                        .HasForeignKey("FabricanteCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloDispositivo", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.Fabricante", null)
                        .WithMany()
                        .HasForeignKey("FabricanteCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Intervenciones.FichaVidaUtil", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Intervenciones.Intervencion", null)
                        .WithMany()
                        .HasForeignKey("IntervencionCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Intervenciones.Intervencion", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.Agregado", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.Evento", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Monitoreo.ReglaDerivacion", null)
                        .WithMany()
                        .HasForeignKey("ReglaDerivacionCodigo", "ReglaVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.Muestra", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Monitoreo.SesionSondeo", null)
                        .WithMany()
                        .HasForeignKey("SesionSondeoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.PruebaBateria", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Vinculos.MontajeBateria", null)
                        .WithMany()
                        .HasForeignKey("MontajeBateriaCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Monitoreo.SesionSondeo", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Monitoreo.FuenteDatos", null)
                        .WithMany()
                        .HasForeignKey("FuenteDatosCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.CoberturaHost", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("HostCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.MontajeBateria", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("BateriaCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Bateria", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.ModeloBateria", null)
                        .WithMany()
                        .HasForeignKey("ModeloBateriaCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Dispositivo", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.ModeloDispositivo", null)
                        .WithMany()
                        .HasForeignKey("ModeloDispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
