// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAI.Service.Core.Infrastructure.Persistencia;

#nullable disable

namespace SAI.Service.Core.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(SaiDbContext))]
    [Migration("20260721231827_EsquemaEquipos")]
    partial class EsquemaEquipos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.Fabricante", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Identificado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Fabricante", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloBateria", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CapacidadAh")
                        .HasColumnType("REAL");

                    b.Property<string>("FabricanteCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tecnologia")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TemperaturaReferenciaC")
                        .HasColumnType("REAL");

                    b.Property<double?>("TensionNominalV")
                        .HasColumnType("REAL");

                    b.Property<double?>("VidaFlotacionAniosMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("VidaFlotacionAniosMin")
                        .HasColumnType("REAL");

                    b.HasKey("Codigo");

                    b.HasIndex("FabricanteCodigo");

                    b.ToTable("ModeloBateria", null, t =>
                        {
                            t.HasCheckConstraint("CK_ModeloBateria_VidaTemp", "\"VidaFlotacionAniosMin\" IS NULL AND \"VidaFlotacionAniosMax\" IS NULL OR \"TemperaturaReferenciaC\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloDispositivo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FabricanteCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineaTopologia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TensionNominalV")
                        .HasColumnType("REAL");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PotenciaVaNominal", "SAI.Service.Core.Domain.Catalogo.ModeloDispositivo.PotenciaVaNominal#Valor<double>", b1 =>
                        {
                            b1.Property<double>("Contenido")
                                .HasColumnType("REAL")
                                .HasColumnName("PotenciaVaNominalValor");

                            b1.Property<string>("Origen")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PotenciaVaNominalOrigen");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("FabricanteCodigo");

                    b.ToTable("ModeloDispositivo", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.UnidadFisica", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FechaBaja")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoBaja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("Tipo", "Estado");

                    b.ToTable("UnidadFisica", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator<string>("Tipo").HasValue("UnidadFisica");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Verificaciones.Verificacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supuesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VigenciaHasta")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Verificacion", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.CoberturaHost", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Vigencia", "SAI.Service.Core.Domain.Vinculos.CoberturaHost.Vigencia#Vigencia", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Desde")
                                .HasColumnType("TEXT")
                                .HasColumnName("Desde");

                            b1.Property<DateTimeOffset?>("Hasta")
                                .HasColumnType("TEXT")
                                .HasColumnName("Hasta");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("DispositivoCodigo");

                    b.HasIndex("HostCodigo")
                        .IsUnique()
                        .HasFilter("\"Hasta\" IS NULL");

                    b.ToTable("CoberturaHost", null, t =>
                        {
                            t.HasCheckConstraint("CK_CoberturaHost_Intervalo", "\"Hasta\" IS NULL OR \"Hasta\" >= \"Desde\"");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.MontajeBateria", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("BateriaCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Vigencia", "SAI.Service.Core.Domain.Vinculos.MontajeBateria.Vigencia#Vigencia", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Desde")
                                .HasColumnType("TEXT")
                                .HasColumnName("Desde");

                            b1.Property<DateTimeOffset?>("Hasta")
                                .HasColumnType("TEXT")
                                .HasColumnName("Hasta");
                        });

                    b.HasKey("Codigo");

                    b.HasIndex("BateriaCodigo");

                    b.HasIndex("DispositivoCodigo", "Posicion")
                        .IsUnique()
                        .HasFilter("\"Hasta\" IS NULL");

                    b.ToTable("MontajeBateria", null, t =>
                        {
                            t.HasCheckConstraint("CK_MontajeBateria_Intervalo", "\"Hasta\" IS NULL OR \"Hasta\" >= \"Desde\"");
                        });
                });

            modelBuilder.Entity("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Bateria", b =>
                {
                    b.HasBaseType("SAI.Service.Core.Domain.Inventario.UnidadFisica");

                    b.Property<DateOnly?>("FechaCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaFabricacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloBateriaCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("ModeloBateriaCodigo");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Bateria");
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Dispositivo", b =>
                {
                    b.HasBaseType("SAI.Service.Core.Domain.Inventario.UnidadFisica");

                    b.Property<string>("ModeloDispositivoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("TEXT");

                    b.HasIndex("ModeloDispositivoCodigo");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Dispositivo");
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Host", b =>
                {
                    b.HasBaseType("SAI.Service.Core.Domain.Inventario.UnidadFisica");

                    b.Property<string>("Criticidad")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EnServicioDesde")
                        .HasColumnType("TEXT");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_UnidadFisica_Baja", "(\"Estado\" = 'DadoDeBaja') = (\"FechaBaja\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Host");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SAI.Service.Core.Infrastructure.Persistencia.AdministradorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloBateria", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.Fabricante", null)
                        .WithMany()
                        .HasForeignKey("FabricanteCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Catalogo.ModeloDispositivo", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.Fabricante", null)
                        .WithMany()
                        .HasForeignKey("FabricanteCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.CoberturaHost", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("HostCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Vinculos.MontajeBateria", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("BateriaCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAI.Service.Core.Domain.Inventario.UnidadFisica", null)
                        .WithMany()
                        .HasForeignKey("DispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Bateria", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.ModeloBateria", null)
                        .WithMany()
                        .HasForeignKey("ModeloBateriaCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAI.Service.Core.Domain.Inventario.Dispositivo", b =>
                {
                    b.HasOne("SAI.Service.Core.Domain.Catalogo.ModeloDispositivo", null)
                        .WithMany()
                        .HasForeignKey("ModeloDispositivoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
