// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SAI.Service.Core.Infrastructure.Persistencia;

#nullable disable

namespace SAI.Service.Core.Infrastructure.Persistencia.Migraciones;

[DbContext(typeof(SaiDbContext))]
[Migration("20260721000001_EsquemaInicialAcceso")]
partial class EsquemaInicialAcceso
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        ModeloIdentityBuilder.Construir(modelBuilder);
#pragma warning restore 612, 618
    }
}
