// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SAI.Service.Core.Infrastructure.Persistencia;

#nullable disable

namespace SAI.Service.Core.Infrastructure.Persistencia.Migraciones;

[DbContext(typeof(SaiDbContext))]
partial class SaiDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        ModeloIdentityBuilder.Construir(modelBuilder);
#pragma warning restore 612, 618
    }
}
